<!-- # <span style="color:#FFFFFF; font-size: 0%;">1 | Introduction</span>
<div style="border-radius: 0px; background-color: #112241; text-align:center;">
    <h4 style="color: white; padding: 1.5rem; font-size: 19px"><b>1 | INTRODUCTION</b></h4>
</div>
<!-- <br> -->

<div style="display: flex; flex-direction: row; align-items: center;">
    <div style="flex : 0; margin-top: 10px;">
        <img src="https://wallpaperaccess.com/full/2355536.jpg" alt="Image" style="max-width: 400px; max-height540px;" />
    </div>
    <div style="flex: 1; margin-left: 26px; margin-top: 7px">
        <h1><b>Data Alchemy: Decoding Iris Insights 🔍✨</b></h1>

Hi, I am <h3><b>Saman Fatima</b></h3> Welcome! This concise notebook navigates through the Iris dataset, offering insightful exploratory data analysis, handling null values and outliers, and implementing effective machine learning techniques. Designed with beginners in mind.
<br>
<blockquote> your upvote serves as motivation! 👍🚀
    </div>
</div>


## **Table of Contents**

1. [About The Author](#1-about-the-author)
2. [About The Data](#2-about-the-data)
   - [About the Columns](#about-the-columns)
   - [Empowering Solutions](#empowering-solutions)
   - [Let's Begin !!!](#lets-begin-)
3. [Overview of Data](#overview-of-data)
4. [Dealing With Outliers](#dealing-with-outliers)
5. [Getting Data without Outliers and Merging with Actual Data](#getting-data-without-outliers-and-merging-with-actual-data)
6. [Checking Unique and Inconsistencies in the Data](#checking-unique-and-inconsistencies-in-the-data)
7. [Changing Data Type](#changing-data-type)
8. [Choosing the Right Model](#choosing-the-right-model)
9. [Saving and Predicting The Model](#saving-and-predicting-the-model)
10. [Conclusion](#Conclusion)


## **Stay Connected for More Insights 🌐🔗**

[Facebook](https://www.facebook.com/saman.fatima.50364592/)

[Email](samanfatimgmail.cm)

[Github](https://github.com/SamanFatima7)

[kaggle](https://www.kaggle.com/samanfatima7)

[Linkedin](https://www.linkedin.com/in/saman-fatima-datascience/)

[Twitter](https://twitter.com/SamanFatima9106)

# **2. About The Data**

- To get the Iris dataset in Python, you can use the Seaborn library's load_dataset function.

- > pip install seaborn  
- > import seaborn as sns
- > iris_data = sns.load_dataset('iris')

#### ***About the Columns***

1. **Sepal Length (cm):**
   - *Description:* Length of the iris flower's sepal (the outermost whorl of a flower).

2. **Sepal Width (cm):**
   - *Description:* Width of the iris flower's sepal.

3. **Petal Length (cm):**
   - *Description:* Length of the iris flower's petal (the innermost whorl of a flower).

4. **Petal Width (cm):**
   - *Description:* Width of the iris flower's petal.

5. **Species:**
   - *Description:* The class of the iris flower, indicating its species.
   - *Values:* Setosa, Versicolor, Virginica.

`Empowering Solutions` : ***Simplifying Iris Categorization through Innovative ML Models***

We will built a machine learning model that classifies Iris flowers by analyzing their sepal length, sepal width, petal length, and petal width. This model accurately predicts the Iris flower type, simplifying the categorization process in various applications.

> #### **Let's Begin !!!**

In [1]:
# Loading Important Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

In [2]:
data = pd.read_csv("../input/iris-flower-dataset/IRIS.csv")

In [3]:
# data = pd.read_csv('/Kaggle/input/iris-flower-dataset/IRIS.csv')

In [4]:
# Loading the dataset
# data = sns.load_dataset('Iris')

---
# ***Overview of Data***
---

In [5]:
# Checking the rows and columns
data.shape

(150, 5)

In [6]:
# Checking Null/Non Null and Data types of Columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [7]:
# Taking a quick look on the data 
data.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
# Checking the null values with their sum 
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [9]:
# Checking columns names
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

---
# ***Dealing With Outliers***
---

In [10]:
# We are using Z score method for checking and removing outliers
# We are just checking one column for better understanding of z-score method
mean = np.mean(data['sepal_width'])
std = np.std(data['sepal_width'])

# Step 1: Calculate the Z-Score
data['width-Z-Score'] = (data['sepal_width'] - mean) / std
data.head(5)

,sepal_length,sepal_width,petal_length,petal_width,species,width-Z-Score
0,5.1,3.5,1.4,0.2,Iris-setosa,1.032057
1,4.9,3.0,1.4,0.2,Iris-setosa,-0.124958
2,4.7,3.2,1.3,0.2,Iris-setosa,0.337848
3,4.6,3.1,1.5,0.2,Iris-setosa,0.106445
4,5.0,3.6,1.4,0.2,Iris-setosa,1.263460

In [11]:
print(f"Here are the outliers based on the z-score threshold, 3:\n {data[data['width-Z-Score'] > 3]}")

Here are the outliers based on the z-score threshold, 3:
     sepal_length  sepal_width  petal_length  petal_width      species  \
15           5.7          4.4           1.5          0.4  Iris-setosa

    width-Z-Score
15       3.114684

In [12]:
# Now we will check all the outliers in these 4 columns
data_1 = data[['sepal_length','sepal_width','petal_length','petal_width']]

# Creating a new dataframe 
data_1 = pd.DataFrame(data_1)

# Calculate mean and standard deviation for all columns
means = data_1.mean()
stds = data_1.std()

# Calculate Z-scores for all columns
z_scores = (data - means) / stds

# Set a threshold for Z-score to identify outliers
threshold = 3  # You can adjust this threshold based on your preference

# Identify rows where any column has an outlier
outliers = (z_scores.abs() > threshold).any(axis=1)

# Display rows with outliers
print("Rows with outliers:")
print(data_1[outliers])

Rows with outliers:
    sepal_length  sepal_width  petal_length  petal_width
15           5.7          4.4           1.5          0.4

In [13]:
df_no_outliers = data_1[~outliers]

# Display the DataFrame without outliers
print("DataFrame without outliers:")
print(df_no_outliers.head(5))

DataFrame without outliers:
   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

---
## ***Getting Data without outliers and merging with actual data***
---

In [14]:
# Merging the data without outliers on the index basis
merged_df = pd.merge(df_no_outliers, data, left_index=True, right_index=True)
merged_df.head(5)

,sepal_length_x,sepal_width_x,petal_length_x,petal_width_x,sepal_length_y,sepal_width_y,petal_length_y,petal_width_y,species,width-Z-Score
0,5.1,3.5,1.4,0.2,5.1,3.5,1.4,0.2,Iris-setosa,1.032057
1,4.9,3.0,1.4,0.2,4.9,3.0,1.4,0.2,Iris-setosa,-0.124958
2,4.7,3.2,1.3,0.2,4.7,3.2,1.3,0.2,Iris-setosa,0.337848
3,4.6,3.1,1.5,0.2,4.6,3.1,1.5,0.2,Iris-setosa,0.106445
4,5.0,3.6,1.4,0.2,5.0,3.6,1.4,0.2,Iris-setosa,1.263460

In [15]:
# Now we will remove Duplicate Columns 
merged_df = merged_df[['sepal_length_x','sepal_width_x','petal_length_x','petal_width_x','species']]

In [16]:
# Removing _x and replacing it in first 4 columns to make column easy to read
merged_df.columns = merged_df.columns.str.replace('_x', '')

In [17]:
# Creating a dataframe without any outliers 
df = merged_df.copy()

In [18]:
# Finnaly we have the data without Outliers 
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

---
# ***Checking Unique and Inconsistencies in the Data***
---

In [19]:
# Checking Nan and All unique values so that if there is inconsistency in the data we will figure it out 
unique_summary = df.apply(lambda col: col.unique())
print(unique_summary)

sepal_length    [5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.4, 4.8, 4.3, ...
sepal_width     [3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, ...
petal_length    [1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1.0, 1.9, ...
petal_width     [0.2, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, ...
species            [Iris-setosa, Iris-versicolor, Iris-virginica]
dtype: object

---
### ***Changing Data Type***
---

In [20]:
df['species'].dtype

dtype('O')

In [21]:
# Changing the Data type of species from Object to Category
df['species'] = df['species'].astype('category')
df['species'].dtype

CategoricalDtype(categories=['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], ordered=False)

---
# ***Choosing the right model***
---

In [22]:
# Load a data and defining X  Features and y Labels)
X = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = data['species']

# Testing Different Models and selecting one on the basis of Accuracy Score 
models = {
    'LogisticRegression': (LogisticRegression(), {'C': [0.1, 1, 10]}),
    'KNeighborsClassifier': (KNeighborsClassifier(), {'n_neighbors': range(1, 21)}),
    'DecisionTreeClassifier': (DecisionTreeClassifier(random_state=42), {'max_depth': [None, 5, 10]}),
    'RandomForestClassifier': (RandomForestClassifier(random_state=42), {'n_estimators': [10, 50, 100], 'max_depth': [None, 5, 10, 15]}),
}

model_results = {}

# Apply feature scaling within the cross-validation loop
for name, (model, params) in models.items():
    # Create a pipeline with a StandardScaler and the model
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('model', GridSearchCV(model, params, cv=5, scoring='accuracy', n_jobs=-1))
    ])
    
    # Use cross_val_score for cross-validation 
    cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring='accuracy')
    mean_cv_accuracy = cv_scores.mean()
    
    pipeline.fit(X, y)
    best_model = pipeline.named_steps['model'].best_estimator_
    
    model_results[name] = {'Cross-Validation Accuracy': mean_cv_accuracy}
    
    print(f"\nModel: {name}")
    print(f"Cross-Validation Mean Accuracy: {mean_cv_accuracy:.2f}")
    print(f"Best Parameters: {best_model.get_params()}")

best_model_name = max(model_results, key=lambda model: model_results[model]['Cross-Validation Accuracy'])

print(f"\nBest Model: {best_model_name} with Metrics: {model_results[best_model_name]}")

Model: LogisticRegression
Cross-Validation Mean Accuracy: 0.97
Best Parameters: {'C': 10, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}

Model: KNeighborsClassifier
Cross-Validation Mean Accuracy: 0.95
Best Parameters: {'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 6, 'p': 2, 'weights': 'uniform'}

Model: DecisionTreeClassifier
Cross-Validation Mean Accuracy: 0.95
Best Parameters: {'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'random_state': 42, 'splitter': 'best'}

Model: RandomForestClassifier
Cross-Validation Mean Accuracy: 0.96
Best Parameters: {'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 50, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

Best Model: LogisticRegression with Metrics: {'Cross-Validation Accuracy': 0.9733333333333334}

> ### ***According to the results `Best Model` is `LogisticRegression` with  `Accuracy: 0.9733333333333334`***

---
# ***Saving and Predicting The Model***
---

In [23]:
# Saving the model
import pickle
save_path = r'C:\Users\Mr.J10\Desktop\Full_Model\Iris_model_02.pkl'
with open(save_path, 'wb') as file:
    pickle.dump(best_model, file)

In [24]:
# Loading the model
import pickle
save_path = r'C:\Users\Mr.J10\Desktop\Full_Model\Iris_model_02.pkl'
model_load = pickle.load(open(save_path, 'rb'))

In [25]:
# Predicting the model
model_load.predict([[4.6,3.1,1.5,0.2]])

array(['Iris-virginica'], dtype=object)

---
# ***Conclusion***
---


> In a nutshell, our smart computer program is really good at figuring out what kind of Iris flower it is. It looks at things like how long and wide the petals and sepals are. This helps a lot in sorting out the flowers quickly and correctly. It's like a helpful tool that makes it easier to know which Iris flower is which, and it can be used in different situations where we need to tell them apart.